"""Zero-shot detection with Binoculars (Hans et al., 2024) using a Russian-capable model pair.

score(s) = PPL_performer(s) / X-PPL(observer, performer)(s)
  PPL   : perplexity of the text under the performer model
  X-PPL : cross-perplexity, the expected surprise of the performer under the observer's
          next-token distribution, averaged over tokens
Low score -> machine. Follows the reference implementation (observer = base model,
performer = instruct model of the same family, shared tokenizer).

The decision threshold is fitted on the CoAT dev split; AUROC is threshold-free.
Per-text scores are saved so they can be reused as features later.

Usage:
    python scripts/binoculars.py --observer Qwen/Qwen3-4B-Base --performer Qwen/Qwen3-4B --quant nf4 --tag qwen3_4b
    python scripts/binoculars.py ... --quant bf16          # on a big GPU
    python scripts/binoculars.py ... --limit 300           # smoke test
"""
import argparse
import gc
import os
import sys
import time
from pathlib import Path

os.environ.setdefault("HF_HOME", r"E:\hf_cache")
os.environ.setdefault("HF_HUB_DISABLE_SYMLINKS_WARNING", "1")
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig

from src.data import get_splits
from src.evaluate import report
from src.external_data import load_ainl, load_llmtrace_ru

ROOT = Path(__file__).resolve().parents[1]
SCORES_DIR = ROOT / "outputs" / "scores"


def load_model(name, quant, device):
    if quant == "nf4":
        cfg = BitsAndBytesConfig(load_in_4bit=True, bnb_4bit_quant_type="nf4",
                                 bnb_4bit_compute_dtype=torch.bfloat16, bnb_4bit_use_double_quant=True)
        return AutoModelForCausalLM.from_pretrained(name, quantization_config=cfg, device_map={"": 0})
    return AutoModelForCausalLM.from_pretrained(name, dtype=torch.bfloat16).to(device)


@torch.no_grad()
def binoculars_scores(texts, tok, observer, performer, max_len, bs, device):
    """Scores in the original order; texts are processed sorted by length to minimise padding."""
    texts = list(texts)
    order = np.argsort([len(t) for t in texts])
    out = np.empty(len(texts), dtype=np.float32)
    for i in range(0, len(texts), bs):
        idx = order[i:i + bs]
        enc = tok([texts[j] for j in idx], return_tensors="pt", padding=True, truncation=True, max_length=max_len).to(device)
        obs_logits = observer(**enc).logits[:, :-1].float()
        perf_logits = performer(**enc).logits[:, :-1].float()
        labels = enc.input_ids[:, 1:]
        mask = enc.attention_mask[:, 1:].float()

        nll = F.cross_entropy(perf_logits.transpose(1, 2), labels, reduction="none")
        ppl = (nll * mask).sum(1) / mask.sum(1)

        p_obs = F.softmax(obs_logits, dim=-1)
        logq_perf = F.log_softmax(perf_logits, dim=-1)
        xent = -(p_obs * logq_perf).sum(-1)
        x_ppl = (xent * mask).sum(1) / mask.sum(1)

        out[idx] = (ppl / x_ppl).cpu().numpy()
    return out


def sanity_check(tok, observer, performer, max_len, device):
    """Score direction check: a text generated by the performer itself must score lower than human text."""
    human = ("Отношения Гапона с эсерами также порвались в сентябре 1905 года. Он уехал в Финляндию, "
             "где жил на даче у знакомых, и почти ни с кем не переписывался.")
    msgs = [{"role": "user", "content": "Напиши абзац из четырёх предложений о жизни в русской деревне в XIX веке."}]
    ids = tok.apply_chat_template(msgs, add_generation_prompt=True, return_tensors="pt", enable_thinking=False).to(device)
    gen = performer.generate(ids, max_new_tokens=120, do_sample=True, temperature=0.7, top_p=0.9)
    machine = tok.decode(gen[0, ids.shape[1]:], skip_special_tokens=True).strip()
    s = binoculars_scores([human, machine], tok, observer, performer, max_len, 2, device)
    print(f"sanity: human score {s[0]:.3f} | machine score {s[1]:.3f} -> {'OK (machine lower)' if s[1] < s[0] else 'INVERTED'}")
    print("machine sample:", machine[:200].replace("\n", " "), flush=True)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--observer", default="Qwen/Qwen3-4B-Base")
    ap.add_argument("--performer", default="Qwen/Qwen3-4B")
    ap.add_argument("--quant", choices=["nf4", "bf16"], default="nf4")
    ap.add_argument("--tag", default="qwen3_4b")
    ap.add_argument("--max_len", type=int, default=256)
    ap.add_argument("--bs", type=int, default=16)
    ap.add_argument("--limit", type=int, default=0, help="smoke test: N texts per set, nothing saved")
    ap.add_argument("--sample", type=int, default=0, help="score a fixed random sample of N texts per set (saved)")
    ap.add_argument("--sanity", action="store_true", help="only run the score-direction check")
    args = ap.parse_args()

    device = torch.device("cuda")
    tok = AutoTokenizer.from_pretrained(args.observer, padding_side="right")
    if tok.pad_token is None:
        tok.pad_token = tok.eos_token
    observer = load_model(args.observer, args.quant, device).eval()
    performer = load_model(args.performer, args.quant, device).eval()
    gc.collect()
    torch.cuda.empty_cache()
    print(f"loaded pair in {args.quant}; GPU mem {torch.cuda.memory_allocated()/1e9:.1f} GB", flush=True)
    if args.sanity:
        sanity_check(tok, observer, performer, args.max_len, device)
        return

    _, coat_dev, coat_test = get_splits()
    llm = load_llmtrace_ru()
    ainl = load_ainl()
    sets = {
        "coat_dev": coat_dev,
        "coat_test": coat_test,
        "llmtrace_test": llm[llm.split == "test"].reset_index(drop=True),
        "ainl_test": ainl[ainl.split == "test"].reset_index(drop=True),
    }
    n = args.limit or args.sample
    if n:
        sets = {k: v.sample(min(len(v), n), random_state=0).reset_index(drop=True) for k, v in sets.items()}

    run = f"binoculars_{args.tag}_{args.quant}" + (f"_s{args.sample}" if args.sample else "")
    SCORES_DIR.mkdir(parents=True, exist_ok=True)
    threshold = None
    for name, df in sets.items():
        t0 = time.time()
        s = binoculars_scores(df.text.values, tok, observer, performer, args.max_len, args.bs, device)
        print(f"{name}: {len(df)} texts, {time.time()-t0:.0f}s", flush=True)
        if not args.limit:
            pd.DataFrame({"id": df.id, "score": s}).to_parquet(SCORES_DIR / f"{run}__{name}.parquet", index=False)
        if name == "coat_dev":
            cands = np.quantile(s, np.linspace(0.01, 0.99, 197))
            accs = [((s < t).astype(int) == df.label.values).mean() for t in cands]
            threshold = float(cands[int(np.argmax(accs))])
            print(f"threshold fitted on coat_dev: {threshold:.4f} (dev acc {max(accs):.4f})", flush=True)
        report(run, name, df, (s < threshold).astype(int), -s, save=not args.limit)


if __name__ == "__main__":
    main()
